/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PatientInsurancePolicy struct {
	TypeName string `json:"type_name"`
	ContractTitle string `json:"contract_title"`
	ContractIsActive bool `json:"contract_is_active"`
	IsActive bool `json:"is_active"`
	Created string `json:"created"`
	Type_ *AllOfPatientInsurancePolicyType_ `json:"type,omitempty"`
	Series string `json:"series,omitempty"`
	Number string `json:"number,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	EndDate string `json:"end_date,omitempty"`
	IsDefault bool `json:"is_default,omitempty"`
	InsuranceState int32 `json:"insurance_state"`
	Okato string `json:"okato,omitempty"`
	MedicalHealthcareState string `json:"medical_healthcare_state,omitempty"`
	Contract int32 `json:"contract,omitempty"`
}
