/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PatchedPatientPreorder struct {
	Id int32 `json:"id,omitempty"`
	Uid string `json:"uid,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	// Patient full name: first, last & middle
	PatientName string `json:"patient_name,omitempty"`
	// Digits only
	MobilePhone string `json:"mobile_phone,omitempty"`
	Comment string `json:"comment,omitempty"`
	Expiration string `json:"expiration,omitempty"`
	PaymentType *AllOfPatchedPatientPreorderPaymentType `json:"payment_type,omitempty"`
	Count int32 `json:"count,omitempty"`
	CompletedCount int32 `json:"completed_count,omitempty"`
	Price string `json:"price,omitempty"`
	TotalPaid string `json:"total_paid,omitempty"`
	Deleted bool `json:"deleted,omitempty"`
	DeletedTime string `json:"deleted_time,omitempty"`
	Confirmed bool `json:"confirmed,omitempty"`
	Status *AllOfPatchedPatientPreorderStatus `json:"status,omitempty"`
	WarrantyNumber string `json:"warranty_number,omitempty"`
	WarrantyDate string `json:"warranty_date,omitempty"`
	WarrantyIsAgreed bool `json:"warranty_is_agreed,omitempty"`
	Branch int32 `json:"branch,omitempty"`
	Timeslot int32 `json:"timeslot,omitempty"`
	Visit int32 `json:"visit,omitempty"`
	// List of services
	Service int32 `json:"service,omitempty"`
	InsurancePolicy int32 `json:"insurance_policy,omitempty"`
	Promotion int32 `json:"promotion,omitempty"`
	Card int32 `json:"card,omitempty"`
	MedicalPlan int32 `json:"medical_plan,omitempty"`
	Region int32 `json:"region,omitempty"`
	WarrantyDocument int32 `json:"warranty_document,omitempty"`
}
