/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// CtypeEnum : * `visit` - visit * `medicalplan` - medicalplan * `certificate` - certificate
type CtypeEnum string

// List of CtypeEnum
const (
	VISIT_CtypeEnum CtypeEnum = "visit"
	MEDICALPLAN_CtypeEnum CtypeEnum = "medicalplan"
	CERTIFICATE_CtypeEnum CtypeEnum = "certificate"
)
