/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StaffDaySchedule struct {
	Day int32 `json:"day"`
	Start string `json:"start,omitempty"`
	End string `json:"end,omitempty"`
}
