/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// BaseServiceTypeEnum : * `cons` - консультативная услуга * `man` - манипуляция * `exam` - обследование * `lab` - лабораторная услуга * `diag` - диагностические исследования * `article` - товар * `material` - материал * `group` - группа * `addval` - дополнительная услуга * `archive` - архив
type BaseServiceTypeEnum string

// List of BaseServiceTypeEnum
const (
	CONS_BaseServiceTypeEnum BaseServiceTypeEnum = "cons"
	MAN_BaseServiceTypeEnum BaseServiceTypeEnum = "man"
	EXAM_BaseServiceTypeEnum BaseServiceTypeEnum = "exam"
	LAB_BaseServiceTypeEnum BaseServiceTypeEnum = "lab"
	DIAG_BaseServiceTypeEnum BaseServiceTypeEnum = "diag"
	ARTICLE_BaseServiceTypeEnum BaseServiceTypeEnum = "article"
	MATERIAL_BaseServiceTypeEnum BaseServiceTypeEnum = "material"
	GROUP_BaseServiceTypeEnum BaseServiceTypeEnum = "group"
	ADDVAL_BaseServiceTypeEnum BaseServiceTypeEnum = "addval"
	ARCHIVE_BaseServiceTypeEnum BaseServiceTypeEnum = "archive"
)
