/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PatientCertificate struct {
	Id int32 `json:"id"`
	Created string `json:"created"`
	NumberText string `json:"number_text,omitempty"`
	Type_ *AllOfPatientCertificateType_ `json:"type,omitempty"`
	Price float64 `json:"price,omitempty"`
	Discount float64 `json:"discount,omitempty"`
	DiscountPercent int32 `json:"discount_percent,omitempty"`
	Balance float64 `json:"balance,omitempty"`
	Office int32 `json:"office"`
}
