/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// DirectionEnum : * `1` - Приходный * `2` - Расходный
type DirectionEnum string

// List of DirectionEnum
const (
	1__DirectionEnum DirectionEnum = "1"
	2__DirectionEnum DirectionEnum = "2"
)
