/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PatchedPatientPayment struct {
	Office int32 `json:"office,omitempty"`
	DocDate string `json:"doc_date,omitempty"`
	ClientAccount int32 `json:"client_account,omitempty"`
	Amount string `json:"amount,omitempty"`
	PaymentType *PatientPaymentPaymentTypeEnum `json:"payment_type,omitempty"`
	Document *PaymentDocument `json:"document,omitempty"`
	Created string `json:"created,omitempty"`
	Direction *AllOfPatchedPatientPaymentDirection `json:"direction,omitempty"`
	ObjectId int64 `json:"object_id,omitempty"`
	Comment string `json:"comment,omitempty"`
	ReceiptNumber string `json:"receipt_number,omitempty"`
	ReceiptReason string `json:"receipt_reason,omitempty"`
	ReceiptQrcode string `json:"receipt_qrcode,omitempty"`
	ReceiptUrl string `json:"receipt_url,omitempty"`
	ContentType int32 `json:"content_type,omitempty"`
	Certificate int32 `json:"certificate,omitempty"`
	Invoice int32 `json:"invoice,omitempty"`
}
