/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// GenderEnum : * `М` - Мужской * `Ж` - Женский
type GenderEnum string

// List of GenderEnum
const (
	_GenderEnum GenderEnum = "М"
	_GenderEnum GenderEnum = "Ж"
)
