/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PatientVisit struct {
	Created string `json:"created"`
	Modified string `json:"modified"`
	Cls *AllOfPatientVisitCls `json:"cls,omitempty"`
	OnDate string `json:"on_date,omitempty"`
	PregnancyWeek int32 `json:"pregnancy_week,omitempty"`
	MensesDay int32 `json:"menses_day,omitempty"`
	Menopause bool `json:"menopause,omitempty"`
	Diagnosis string `json:"diagnosis,omitempty"`
	Sampled string `json:"sampled,omitempty"`
	Status *OneOfPatientVisitStatus `json:"status,omitempty"`
	Specimen string `json:"specimen,omitempty"`
	TotalPrice string `json:"total_price,omitempty"`
	TotalPaid string `json:"total_paid,omitempty"`
	PaymentType *AllOfPatientVisitPaymentType `json:"payment_type,omitempty"`
	DiscountValue string `json:"discount_value,omitempty"`
	TotalDiscount string `json:"total_discount,omitempty"`
	IsCito bool `json:"is_cito,omitempty"`
	Comment string `json:"comment,omitempty"`
	SendToEmail bool `json:"send_to_email,omitempty"`
	OmsReferralNumber string `json:"oms_referral_number,omitempty"`
	OmsReferralDate string `json:"oms_referral_date,omitempty"`
	Operator int32 `json:"operator"`
	Office int32 `json:"office"`
	Contractor int32 `json:"contractor,omitempty"`
	Patient int32 `json:"patient"`
	// Указать кто направил
	Referral int32 `json:"referral,omitempty"`
	ReferralBranch int32 `json:"referral_branch,omitempty"`
	Payer int32 `json:"payer,omitempty"`
	// Выбрать лабораторию, из которой поступил материал
	SourceLab int32 `json:"source_lab,omitempty"`
	Barcode int32 `json:"barcode,omitempty"`
	InsurancePolicy int32 `json:"insurance_policy,omitempty"`
	Discount int32 `json:"discount,omitempty"`
	Contract int32 `json:"contract,omitempty"`
	MedicalRecord int32 `json:"medical_record,omitempty"`
	OmsReferralState string `json:"oms_referral_state,omitempty"`
}
