/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// PaymentType14bEnum : * `н` - Касса * `б` - Юридическое лицо * `д` - ДМС * `к` - Корпоративные расчеты * `о` - ОМС * `э` - ЭКО * `1` - ДП
type PaymentType14bEnum string

// List of PaymentType14bEnum
const (
	_PaymentType14bEnum PaymentType14bEnum = "н"
	_PaymentType14bEnum PaymentType14bEnum = "б"
	_PaymentType14bEnum PaymentType14bEnum = "д"
	_PaymentType14bEnum PaymentType14bEnum = "к"
	_PaymentType14bEnum PaymentType14bEnum = "о"
	_PaymentType14bEnum PaymentType14bEnum = "э"
	1__PaymentType14bEnum PaymentType14bEnum = "1"
)
