/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Application struct {
	Patient string `json:"patient"`
	DtCreated string `json:"dt_created"`
	ExtId string `json:"ext_id,omitempty"`
	Vendor int32 `json:"vendor"`
}
