/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Staff struct {
	Id int32 `json:"id"`
	LastName string `json:"last_name"`
	FirstName string `json:"first_name"`
	MidName string `json:"mid_name,omitempty"`
	Degree string `json:"degree,omitempty"`
	Category string `json:"category,omitempty"`
	Directions string `json:"directions,omitempty"`
	Education string `json:"education,omitempty"`
	HighSchool string `json:"high_school,omitempty"`
	// Год начала общемедицинского стажа
	MedicalExperience int32 `json:"medical_experience,omitempty"`
	MedicalExperienceYears int32 `json:"medical_experience_years"`
	// Год начала работы по основной специальности
	SpecialityExperience int32 `json:"speciality_experience,omitempty"`
	SpecialityExperienceYears int32 `json:"speciality_experience_years"`
	Speciality string `json:"speciality,omitempty"`
	OnlineBookingAllowed bool `json:"online_booking_allowed"`
}
