/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExtendedServiceInline struct {
	ExtId int32 `json:"ext_id"`
	State int32 `json:"state"`
	Offices []int32 `json:"offices"`
	Staff []int32 `json:"staff"`
	Value string `json:"value"`
	IsBookable bool `json:"is_bookable"`
}
