/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServiceInformation struct {
	Code string `json:"code,omitempty"`
	Name string `json:"name"`
	ExecutionTime int32 `json:"execution_time,omitempty"`
	Group string `json:"group"`
	Specimens []Specimen `json:"specimens"`
}
