/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Certificate struct {
	Id int32 `json:"id"`
	Price string `json:"price"`
	Patient string `json:"patient,omitempty"`
	Created string `json:"created"`
	NumberText string `json:"number_text,omitempty"`
	Type_ *AllOfCertificateType_ `json:"type"`
	Discount float64 `json:"discount"`
	DiscountPercent int32 `json:"discount_percent"`
	Balance float64 `json:"balance"`
	Office int32 `json:"office"`
}
