/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PromotionItemInline struct {
	Name string `json:"name"`
	Code string `json:"code"`
	Count int32 `json:"count,omitempty"`
}
