/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Promotion struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Services []PromotionItemInline `json:"services"`
	StartDate string `json:"start_date"`
	EndDate string `json:"end_date"`
	TotalPrice string `json:"total_price"`
	FullPrice string `json:"full_price"`
	// Условия акции
	Comment string `json:"comment,omitempty"`
	Discount int32 `json:"discount,omitempty"`
	// Устанавливается только в том случае, когда необходимо ограничить список офисов в которых может оформляться акция/комплексная услуга
	State []int32 `json:"state,omitempty"`
}
