/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PatientDetail struct {
	Guardianship []string `json:"guardianship"`
	GuardianPatient string `json:"guardian_patient"`
	Created string `json:"created"`
	LastName string `json:"last_name"`
	FirstName string `json:"first_name"`
	MidName string `json:"mid_name,omitempty"`
	BirthDay string `json:"birth_day,omitempty"`
	Gender *OneOfPatientDetailGender `json:"gender,omitempty"`
	WorkPhone string `json:"work_phone,omitempty"`
	HomePhone string `json:"home_phone,omitempty"`
	MobilePhone string `json:"mobile_phone,omitempty"`
	Email string `json:"email,omitempty"`
	AccomodationAddressStreet string `json:"accomodation_address_street,omitempty"`
	HomeAddressStreet string `json:"home_address_street,omitempty"`
	WorkAddressStreet string `json:"work_address_street,omitempty"`
	AccomodationAddressData string `json:"accomodation_address_data,omitempty"`
	HomeAddressData string `json:"home_address_data,omitempty"`
	WorkAddressData string `json:"work_address_data,omitempty"`
	Guardian string `json:"guardian,omitempty"`
	IdCardType *OneOfPatientDetailIdCardType `json:"id_card_type,omitempty"`
	IdCardSeries string `json:"id_card_series,omitempty"`
	IdCardNumber string `json:"id_card_number,omitempty"`
	IdCardIssueDate string `json:"id_card_issue_date,omitempty"`
	IdCardOrg string `json:"id_card_org,omitempty"`
	IdCardDepcode string `json:"id_card_depcode,omitempty"`
	Uid string `json:"uid,omitempty"`
	Modified string `json:"modified"`
	LastNameLat string `json:"last_name_lat,omitempty"`
	FirstNameLat string `json:"first_name_lat,omitempty"`
	MidNameLat string `json:"mid_name_lat,omitempty"`
	HidCard string `json:"hid_card,omitempty"`
	InitialAccount string `json:"initial_account,omitempty"`
	BilledAccount string `json:"billed_account,omitempty"`
	Doc string `json:"doc,omitempty"`
	Balance float64 `json:"balance,omitempty"`
	PreorderNotify *AllOfPatientDetailPreorderNotify `json:"preorder_notify,omitempty"`
	AssignmentNotify *AllOfPatientDetailAssignmentNotify `json:"assignment_notify,omitempty"`
	LabNotify *AllOfPatientDetailLabNotify `json:"lab_notify,omitempty"`
	Snils string `json:"snils,omitempty"`
	IntPassportSeries string `json:"int_passport_series,omitempty"`
	IntPassportNumber string `json:"int_passport_number,omitempty"`
	IntPassportIssueDate string `json:"int_passport_issue_date,omitempty"`
	IntPassportExpDate string `json:"int_passport_exp_date,omitempty"`
	IntPassportOrg string `json:"int_passport_org,omitempty"`
	SendElectronicReceipt *OneOfPatientDetailSendElectronicReceipt `json:"send_electronic_receipt,omitempty"`
	Discount int32 `json:"discount,omitempty"`
	AdSource int32 `json:"ad_source,omitempty"`
	Nationality int32 `json:"nationality,omitempty"`
	DefaultPolicy int32 `json:"default_policy,omitempty"`
	PriceType int32 `json:"price_type,omitempty"`
	Tags []int32 `json:"tags,omitempty"`
}
