/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// PatientOrderedServiceStatusEnum : * `т` - Текущий * `з` - Завершен * `л` - Отправлен в лабораторию * `!` - Ошибка отправки * `>` - В обработке * `?` - На утверждении отмены * `-` - Отмена отклонена * `0` - Отменен
type PatientOrderedServiceStatusEnum string

// List of PatientOrderedServiceStatusEnum
const (
	_PatientOrderedServiceStatusEnum PatientOrderedServiceStatusEnum = "т"
	_PatientOrderedServiceStatusEnum PatientOrderedServiceStatusEnum = "з"
	_PatientOrderedServiceStatusEnum PatientOrderedServiceStatusEnum = "л"
	EXCLAMATION_PatientOrderedServiceStatusEnum PatientOrderedServiceStatusEnum = "!"
	GREATER_THAN_PatientOrderedServiceStatusEnum PatientOrderedServiceStatusEnum = ">"
	QUESTION_MARK_PatientOrderedServiceStatusEnum PatientOrderedServiceStatusEnum = "?"
	MINUS_PatientOrderedServiceStatusEnum PatientOrderedServiceStatusEnum = "-"
	0__PatientOrderedServiceStatusEnum PatientOrderedServiceStatusEnum = "0"
)
