/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// PatientVisitStatusEnum : * `т` - Текущий * `з` - Завершен * `0` - Отменен пациентом * `1` - Отменен врачем * `с` - Сторнирован оператором
type PatientVisitStatusEnum string

// List of PatientVisitStatusEnum
const (
	_PatientVisitStatusEnum PatientVisitStatusEnum = "т"
	_PatientVisitStatusEnum PatientVisitStatusEnum = "з"
	0__PatientVisitStatusEnum PatientVisitStatusEnum = "0"
	1__PatientVisitStatusEnum PatientVisitStatusEnum = "1"
	_PatientVisitStatusEnum PatientVisitStatusEnum = "с"
)
