/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// Type080Enum : * `1` - Подарочный сертификат
type Type080Enum int32

// List of Type080Enum
const (
	1__Type080Enum Type080Enum = "1"
)
