/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Service struct {
	Id int32 `json:"id"`
	State int32 `json:"state"`
	Name string `json:"name"`
	BaseService int32 `json:"base_service"`
	Group *ServiceGroup `json:"group"`
	PriceValue string `json:"price_value"`
	PriceDate string `json:"price_date"`
	Staff []int32 `json:"staff"`
}
