/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Patient struct {
	Uid string `json:"uid"`
	LastName string `json:"last_name"`
	FirstName string `json:"first_name"`
	MidName string `json:"mid_name,omitempty"`
	Gender *GenderEnum `json:"gender"`
	BirthDay string `json:"birth_day"`
	MobilePhone string `json:"mobile_phone,omitempty"`
	Email string `json:"email,omitempty"`
}
