/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Entity struct {
	Id int32 `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
	DateDeprecated string `json:"date_deprecated,omitempty"`
	Parent int32 `json:"parent,omitempty"`
}
