/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PatientCard struct {
	Id int32 `json:"id"`
	Name string `json:"name,omitempty"`
	PrintName string `json:"print_name,omitempty"`
	Created string `json:"created"`
	Modified string `json:"modified"`
	DocDate string `json:"doc_date,omitempty"`
	OrderedService int32 `json:"ordered_service,omitempty"`
	Diagnosis string `json:"diagnosis"`
	VisitNumber int32 `json:"visit_number"`
}
