/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PatientOrderedService struct {
	Created string `json:"created"`
	Modified string `json:"modified"`
	Executed string `json:"executed,omitempty"`
	Price string `json:"price,omitempty"`
	Discount string `json:"discount,omitempty"`
	TotalPrice string `json:"total_price,omitempty"`
	Count int32 `json:"count,omitempty"`
	Status *AllOfPatientOrderedServiceStatus `json:"status,omitempty"`
	PrintDate string `json:"print_date,omitempty"`
	Operator int32 `json:"operator"`
	Order int32 `json:"order"`
	Service int32 `json:"service"`
	ExecutionPlace int32 `json:"execution_place,omitempty"`
	Staff int32 `json:"staff,omitempty"`
	Sampling int32 `json:"sampling,omitempty"`
	Promotion int32 `json:"promotion,omitempty"`
	Assigment int32 `json:"assigment,omitempty"`
	Region int32 `json:"region,omitempty"`
	SpecimenTypes []int32 `json:"specimen_types,omitempty"`
}
