/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LegalEntity struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	ShortName string `json:"short_name,omitempty"`
	// Индекс, регион, населенный пункт, улица, дом
	Address string `json:"address,omitempty"`
	Licenses string `json:"licenses,omitempty"`
	Head string `json:"head,omitempty"`
	// Используются в документах
	HeadTitle string `json:"head_title,omitempty"`
	// Поле ИНН должно содержать 10 (Юр.Лица) или 12 (ИП) знаков
	Inn string `json:"inn,omitempty"`
	// Поле КПП должно содержать 9 знаков
	Kpp string `json:"kpp,omitempty"`
	// Это поле должно содержать 13 знаков для ОГРН или 15 знаков для ОГРНИП
	Ogrn string `json:"ogrn,omitempty"`
	BankDetails string `json:"bank_details,omitempty"`
}
