/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// ClsEnum : * `п` - Посещение * `б` - Биоматериал * `в` - Возврат
type ClsEnum string

// List of ClsEnum
const (
	_ClsEnum ClsEnum = "п"
	_ClsEnum ClsEnum = "б"
	_ClsEnum ClsEnum = "в"
)
