/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Branch struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Address string `json:"address,omitempty"`
	Phones string `json:"phones,omitempty"`
	Schedule string `json:"schedule,omitempty"`
}
