/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// LabNotifyEnum : * `0` - Не уведомлять * `1` - Уведомлять по SMS * `2` - Уведомлять по Email
type LabNotifyEnum int32

// List of LabNotifyEnum
const (
	0__LabNotifyEnum LabNotifyEnum = "0"
	1__LabNotifyEnum LabNotifyEnum = "1"
	2__LabNotifyEnum LabNotifyEnum = "2"
)
