/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BaseService struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Code string `json:"code,omitempty"`
	ExecutionTime int32 `json:"execution_time,omitempty"`
	Type_ *AllOfBaseServiceType_ `json:"type,omitempty"`
	About string `json:"about,omitempty"`
	Indications string `json:"indications,omitempty"`
	Preparation string `json:"preparation,omitempty"`
	Parent int32 `json:"parent,omitempty"`
	BaseGroup int32 `json:"base_group,omitempty"`
	StdCode string `json:"std_code"`
	Prices []ExtendedServiceInline `json:"prices"`
	HasPromotions bool `json:"has_promotions"`
	HasDiscounts bool `json:"has_discounts"`
	HasStaff bool `json:"has_staff"`
	Promotions []int32 `json:"promotions"`
	Discounts []DiscountInline `json:"discounts"`
}
