/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PatchedPatientMedicalPlan struct {
	Id int32 `json:"id,omitempty"`
	Preorders []PatientPreorder `json:"preorders,omitempty"`
	Created string `json:"created,omitempty"`
	Modified string `json:"modified,omitempty"`
	Title string `json:"title,omitempty"`
	DateStart string `json:"date_start,omitempty"`
	DateEnd string `json:"date_end,omitempty"`
	PaymentType *AllOfPatchedPatientMedicalPlanPaymentType `json:"payment_type,omitempty"`
	TotalPrice string `json:"total_price,omitempty"`
	TotalPaid string `json:"total_paid,omitempty"`
	IsCompleted bool `json:"is_completed,omitempty"`
	IsForAppointment bool `json:"is_for_appointment,omitempty"`
	Comment string `json:"comment,omitempty"`
	Office int32 `json:"office,omitempty"`
	BaseGroup int32 `json:"base_group,omitempty"`
	Promotion int32 `json:"promotion,omitempty"`
	MedicalRecord int32 `json:"medical_record,omitempty"`
	InsurancePolicy int32 `json:"insurance_policy,omitempty"`
	Discount int32 `json:"discount,omitempty"`
}
