/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// IdCardTypeEnum : * `1` - Паспорт гражданина РФ * `2` - Заграничный паспорт * `3` - Свидетельство о рождении * `4` - Заграничный паспорт СССР * `5` - Удостоверение личности офицера * `6` - Справка об освобождении из места лишения свободы * `7` - Военный билет * `8` - Дипломатический паспорт РФ * `9` - Иностранный паспорт * `10` - Свидетельство беженца * `11` - Вид на жительство * `12` - Удостоверение беженца * `13` - Временное удостоверение * `14` - Паспорт моряка * `15` - Военный билет офицера запаса * `16` - Паспорт СССР * `17` - Свидетельство о рождении не РФ * `18` - Документ лица без гражданства * `19` - Разрешение на временное проживание * `88` - Иные документы * `99` - Документ не предоставлен
type IdCardTypeEnum string

// List of IdCardTypeEnum
const (
	1__IdCardTypeEnum IdCardTypeEnum = "1"
	2__IdCardTypeEnum IdCardTypeEnum = "2"
	3__IdCardTypeEnum IdCardTypeEnum = "3"
	4__IdCardTypeEnum IdCardTypeEnum = "4"
	5__IdCardTypeEnum IdCardTypeEnum = "5"
	6__IdCardTypeEnum IdCardTypeEnum = "6"
	7__IdCardTypeEnum IdCardTypeEnum = "7"
	8__IdCardTypeEnum IdCardTypeEnum = "8"
	9__IdCardTypeEnum IdCardTypeEnum = "9"
	10__IdCardTypeEnum IdCardTypeEnum = "10"
	11__IdCardTypeEnum IdCardTypeEnum = "11"
	12__IdCardTypeEnum IdCardTypeEnum = "12"
	13__IdCardTypeEnum IdCardTypeEnum = "13"
	14__IdCardTypeEnum IdCardTypeEnum = "14"
	15__IdCardTypeEnum IdCardTypeEnum = "15"
	16__IdCardTypeEnum IdCardTypeEnum = "16"
	17__IdCardTypeEnum IdCardTypeEnum = "17"
	18__IdCardTypeEnum IdCardTypeEnum = "18"
	19__IdCardTypeEnum IdCardTypeEnum = "19"
	88__IdCardTypeEnum IdCardTypeEnum = "88"
	99__IdCardTypeEnum IdCardTypeEnum = "99"
)
