/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Assay struct {
	Barcode string `json:"barcode"`
	SpecimenType string `json:"specimen_type"`
	Services []string `json:"services"`
}
