/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PatientContract struct {
	ContractTypeName string `json:"contract_type_name"`
	Created string `json:"created"`
	Expire string `json:"expire"`
	Active bool `json:"active,omitempty"`
	State int32 `json:"state,omitempty"`
	ContractType int32 `json:"contract_type,omitempty"`
}
