/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Appointment struct {
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
	MiddleName string `json:"middle_name,omitempty"`
	BirthDay string `json:"birth_day,omitempty"`
	// Digits only
	MobilePhone string `json:"mobile_phone"`
	Comment string `json:"comment,omitempty"`
	Timeslot int32 `json:"timeslot"`
	Services []int32 `json:"services"`
}
