/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// RecordTypeEnum : * `1` - Информация о пациенте * `2` - Добавление завершенного случая * `3` - Регистрация случая * `4` - Добавление эпизода * `5` - Добавление медицинских записей * `6` - Закрытие случая * `7` - Изменение закрытого случая
type RecordTypeEnum int32

// List of RecordTypeEnum
const (
	1__RecordTypeEnum RecordTypeEnum = "1"
	2__RecordTypeEnum RecordTypeEnum = "2"
	3__RecordTypeEnum RecordTypeEnum = "3"
	4__RecordTypeEnum RecordTypeEnum = "4"
	5__RecordTypeEnum RecordTypeEnum = "5"
	6__RecordTypeEnum RecordTypeEnum = "6"
	7__RecordTypeEnum RecordTypeEnum = "7"
)
