/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// DiscountInlineTypeEnum : * `promotion` - promotion * `personal` - personal
type DiscountInlineTypeEnum string

// List of DiscountInlineTypeEnum
const (
	PROMOTION_DiscountInlineTypeEnum DiscountInlineTypeEnum = "promotion"
	PERSONAL_DiscountInlineTypeEnum DiscountInlineTypeEnum = "personal"
)
