/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type State struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	OfficialTitle string `json:"official_title"`
	LegalEntity int32 `json:"legal_entity,omitempty"`
	Branch int32 `json:"branch,omitempty"`
	Uuid string `json:"uuid,omitempty"`
}
