/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// PreorderNotifyEnum : * `0` - Не уведомлять * `1` - Уведомлять по SMS * `2` - Уведомлять по Email
type PreorderNotifyEnum int32

// List of PreorderNotifyEnum
const (
	0__PreorderNotifyEnum PreorderNotifyEnum = "0"
	1__PreorderNotifyEnum PreorderNotifyEnum = "1"
	2__PreorderNotifyEnum PreorderNotifyEnum = "2"
)
