/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// Type86cEnum : * `0` - Полис ДМС * `1` - Полис ОМС старого образца * `2` - Временное свидетельство * `3` - Полис ОМС единого образца * `4` - Договор прикрепления
type Type86cEnum int32

// List of Type86cEnum
const (
	0__Type86cEnum Type86cEnum = "0"
	1__Type86cEnum Type86cEnum = "1"
	2__Type86cEnum Type86cEnum = "2"
	3__Type86cEnum Type86cEnum = "3"
	4__Type86cEnum Type86cEnum = "4"
)
