/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StaffDetail struct {
	Id int32 `json:"id"`
	LastName string `json:"last_name"`
	FirstName string `json:"first_name"`
	MidName string `json:"mid_name,omitempty"`
	BirthDay string `json:"birth_day,omitempty"`
	Gender *OneOfStaffDetailGender `json:"gender,omitempty"`
	Photo string `json:"photo,omitempty"`
	Comment string `json:"comment,omitempty"`
	Directions string `json:"directions,omitempty"`
	Education string `json:"education,omitempty"`
	Degree string `json:"degree,omitempty"`
	Category string `json:"category,omitempty"`
	Positions []PositionInline `json:"positions"`
	// Specializations list
	Groups []int32 `json:"groups,omitempty"`
	// Год начала общемедицинского стажа
	MedicalExperience int32 `json:"medical_experience,omitempty"`
	// Год начала работы по основной специальности
	SpecialityExperience int32 `json:"speciality_experience,omitempty"`
	MedicalExperienceYears int32 `json:"medical_experience_years"`
	SpecialityExperienceYears int32 `json:"speciality_experience_years"`
}
