/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DiscountInline struct {
	Type_ *DiscountInlineTypeEnum `json:"type"`
	PromotionId int32 `json:"promotion_id,omitempty"`
	DiscountPercent string `json:"discount_percent,omitempty"`
	DiscountFixed string `json:"discount_fixed,omitempty"`
	Price string `json:"price"`
}
