/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// Status86cEnum : * `0` - Не напоминать * `1` - Напоминать * `2` - Подтверждено * `3` - Перезвонить * `4` - Отправлено СМС
type Status86cEnum int32

// List of Status86cEnum
const (
	0__Status86cEnum Status86cEnum = "0"
	1__Status86cEnum Status86cEnum = "1"
	2__Status86cEnum Status86cEnum = "2"
	3__Status86cEnum Status86cEnum = "3"
	4__Status86cEnum Status86cEnum = "4"
)
