/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Record struct {
	Id int32 `json:"id"`
	Uid string `json:"uid,omitempty"`
	DtCreated string `json:"dt_created,omitempty"`
	DtProcessed string `json:"dt_processed,omitempty"`
	RecordType *AllOfRecordRecordType `json:"record_type"`
	Status *AllOfRecordStatus `json:"status,omitempty"`
	Profile int32 `json:"profile"`
	Patient int32 `json:"patient"`
	Card int32 `json:"card,omitempty"`
	MedicalRecord int32 `json:"medical_record,omitempty"`
}
