/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Profile struct {
	Id int32 `json:"id"`
	Guid string `json:"guid"`
	Idlpu string `json:"idlpu"`
	IsActive bool `json:"is_active,omitempty"`
	State int32 `json:"state"`
}
