/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// Status1d2Enum : * `0` - Новая запись * `1` - Успешно отправлена * `2` - Ошибка отправки
type Status1d2Enum int32

// List of Status1d2Enum
const (
	0__Status1d2Enum Status1d2Enum = "0"
	1__Status1d2Enum Status1d2Enum = "1"
	2__Status1d2Enum Status1d2Enum = "2"
)
