/*
 * MedHQ API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// SendElectronicReceiptEnum : * `email` - На электронную почту * `phone` - По номеру телефона
type SendElectronicReceiptEnum string

// List of SendElectronicReceiptEnum
const (
	EMAIL_SendElectronicReceiptEnum SendElectronicReceiptEnum = "email"
	PHONE_SendElectronicReceiptEnum SendElectronicReceiptEnum = "phone"
)
